spring.application.name=sales-processor-service

# Kafka Streams Configuration
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.properties.application.id=sales-processor-service
spring.kafka.properties.group.id=sales-processor-service-group

# Default serialization/deserialization
spring.kafka.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde

# State store directory
spring.kafka.properties.state.dir=/tmp/kafka-streams

# Logging
logging.level.root=INFO
logging.level.com.data.kata.sales_processor_service=DEBUG
logging.level.org.apache.kafka.streams=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
