services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      OPENLINEAGE_URL: "http://marquez-api:5000"
      OPENLINEAGE_NAMESPACE: "sales-consumer"
    ports:
      - "8082:8080"
    networks:
      - default
      - kafka-shared

networks:
  kafka-shared:
    external: true
    name: ${KAFKA_NETWORK_NAME:-data-processing_default}
